error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: trait must be `unsafe`
  --> tests/ui/crashes/ice-6256.rs:5:1
   |
LL | trait TT {}
   | ^^^^^^^^^^^
   |
   = help: make this trait unsafe: `unsafe trait`
   = note: `-D clippy::safe-code` implied by `-D clippy::safe-fn`
   = help: to override `-D clippy::safe-fn` add `#[allow(clippy::safe_code)]`

error: item must be `pub`
  --> tests/ui/crashes/ice-6256.rs:5:1
   |
LL | trait TT {}
   | ^ help: make this item public: `pub`
   |
   = note: requested on the command line with `-D clippy::missing-pub`

error: item must be `pub`
  --> tests/ui/crashes/ice-6256.rs:7:1
   |
LL | impl dyn TT {
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/crashes/ice-6256.rs:8:5
   |
LL |     fn func(&self) {}
   |     ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/crashes/ice-6256.rs:8:5
   |
LL |     fn func(&self) {}
   |     ^

error: parameter must be `mut`
  --> tests/ui/crashes/ice-6256.rs:8:14
   |
LL |     fn func(&self) {}
   |              ^ help: make this parameter mutable: `mut`
   |
   = note: requested on the command line with `-D clippy::missing-mut`

error: references are not allowed
  --> tests/ui/crashes/ice-6256.rs:8:13
   |
LL |     fn func(&self) {}
   |             ^^^^^
   |
   = help: use a raw pointer instead: `*const`
   = note: requested on the command line with `-D clippy::reference-used`

error: item must be `pub`
  --> tests/ui/crashes/ice-6256.rs:12:1
   |
LL | fn main() {
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/crashes/ice-6256.rs:12:1
   |
LL | fn main() {
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/crashes/ice-6256.rs:12:1
   |
LL | fn main() {
   | ^

error: variable must be `mut`
  --> tests/ui/crashes/ice-6256.rs:13:9
   |
LL |     let f = |x: &dyn TT| x.func();
   |         ^ help: make this variable mutable: `mut`

error: references are not allowed
  --> tests/ui/crashes/ice-6256.rs:13:17
   |
LL |     let f = |x: &dyn TT| x.func();
   |                 ^^^^^^^
   |
   = help: use a raw pointer instead: `*const`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error[E0521]: borrowed data escapes outside of closure
  --> tests/ui/crashes/ice-6256.rs:13:26
   |
LL |     let f = |x: &dyn TT| x.func();
   |              -  -        ^^^^^^^^
   |              |  |        |
   |              |  |        `x` escapes the closure body here
   |              |  |        argument requires that `'1` must outlive `'static`
   |              |  let's call the lifetime of this reference `'1`
   |              `x` is a reference that is only valid in the closure body

error: aborting due to 14 previous errors

For more information about this error, try `rustc --explain E0521`.
