error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: function must be `unsafe`
  --> tests/ui/crashes/ice-6250.rs:8:5
   |
LL | pub fn list_data(cache: &Cache, key: usize) {
   |     ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/crashes/ice-6250.rs:8:5
   |
LL | pub fn list_data(cache: &Cache, key: usize) {
   |     ^
   = note: `-D clippy::safe-code` implied by `-D clippy::safe-fn`
   = help: to override `-D clippy::safe-fn` add `#[allow(clippy::safe_code)]`

error: parameter must be `mut`
  --> tests/ui/crashes/ice-6250.rs:8:18
   |
LL | pub fn list_data(cache: &Cache, key: usize) {
   |                  ^ help: make this parameter mutable: `mut`
   |
   = note: requested on the command line with `-D clippy::missing-mut`

error: parameter must be `mut`
  --> tests/ui/crashes/ice-6250.rs:8:33
   |
LL | pub fn list_data(cache: &Cache, key: usize) {
   |                                 ^ help: make this parameter mutable: `mut`

error: references are not allowed
  --> tests/ui/crashes/ice-6250.rs:8:25
   |
LL | pub fn list_data(cache: &Cache, key: usize) {
   |                         ^^^^^^
   |
   = help: use a raw pointer instead: `*const`
   = note: requested on the command line with `-D clippy::reference-used`

error[E0308]: mismatched types
  --> tests/ui/crashes/ice-6250.rs:12:14
   |
LL |     for reference in vec![1, 2, 3] {
   |         --------- expected due to the type of this binding
...
LL |         Some(reference) = cache.data.get(key) {
   |              ^^^^^^^^^ expected integer, found `&i32`

error[E0308]: mismatched types
  --> tests/ui/crashes/ice-6250.rs:12:9
   |
LL |         Some(reference) = cache.data.get(key) {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bool`, found `()`
   |
help: consider adding `let`
   |
LL |         let Some(reference) = cache.data.get(key) {
   |         +++

error: aborting due to 8 previous errors

For more information about this error, try `rustc --explain E0308`.
